# Generated by Django 3.0.1 on 2020-01-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=64)),
                ('password_md5', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField()),
                ('if_valid', models.BooleanField()),
                ('space', models.IntegerField()),
                ('remain_space', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpaceApply',
            fields=[
                ('apply_id', models.IntegerField(primary_key=True, serialize=False)),
                ('space_gb_number', models.IntegerField()),
                ('reason', models.CharField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
